/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDataList: typeof import('./components/AppDataList.vue')['default']
    AppDrawer: typeof import('./components/AppDrawer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConfirmPrompt: typeof import('./components/ConfirmPrompt.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
